# Generated by Django 4.2.7 on 2023-11-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_investment_maturity_duration_hour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="profit",
            field=models.FloatField(),
        ),
    ]
