# Generated by Django 4.2.7 on 2023-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_investment_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="profit",
            field=models.FloatField(default=0.0),
        ),
    ]
