# Generated by Django 4.2.7 on 2023-11-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_investment_profit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="investment",
            name="profit",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
