# Generated by Django 4.2.7 on 2023-11-24 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_withdraw"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deposit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="withdraw",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
