# Generated by Django 4.2.6 on 2023-10-06 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_account_balance_user_image"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="image",
            new_name="profile_image",
        ),
        migrations.AddField(
            model_name="user",
            name="agree_to_terms_and_condition",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="btc_wallet",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
