# Generated by Django 4.2.7 on 2023-11-14 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_user_account_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account_balance",
            field=models.FloatField(default=0.0),
        ),
    ]
