# Generated by Django 4.2.7 on 2023-11-17 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("referral_system", "0001_initial"),
        ("accounts", "0010_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pending_commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="referral_link",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="user_referral_link",
                to="referral_system.referrallink",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="total_earned_commission",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
