# Generated by Django 4.2.7 on 2023-11-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0015_alter_user_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="earning",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
